
name: Generate Snake

on:
  schedule: # Executa a cada 12 horas
    - cron: "0 */12 * * *"
  workflow_dispatch: # Permite rodar manualmente
  push: # Executa quando houver push
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Gerar animação da cobrinha
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: MOR4Xx
          outputs: |
            dist/github-contribution-grid-snake.svg?palette=github-dark

      - name: Enviar resultado
        uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Action
          author_email: actions@github.com
          message: "Gerando animação da cobrinha"
          add: "dist/github-contribution-grid-snake.svg"
